# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1318929599);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1318929720);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1319742299);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20111008085652");
user_pref("browser.startup.homepage_override.mstone", "rv:7.0.1");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 5);
user_pref("extensions.enabledAddons", "langpack-en-GB@firefox.mozilla.org:7.0.1,langpack-en-ZA@firefox.mozilla.org:7.0.1,globalmenu@ubuntu.com:2.0.1,ubufox@ubuntu.com:1.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:7.0.1");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1319121234000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1318429731000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1318078360000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1318078360000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox-7.0.1/extensions/globalmenu@ubuntu.com\",\"mtime\":1318429731000}}}]");
user_pref("extensions.lastAppVersion", "7.0.1");
user_pref("extensions.lastPlatformVersion", "7.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 124550);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1321521362);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
